GET http://localhost:3939/users/details
Authorization: Bearer 

###

POST http://localhost:3939/users/register
Content-Type: application/json

{
     "username": "",
     "password": ""
}

###

POST http://localhost:3939/users/login
Content-Type: application/json

{
     "username": "",
     "password": ""
}

###

GET http://localhost:3939/tasks/
Authorization: Bearer 


###

POST http://localhost:3939/tasks/
Content-Type: application/json
Authorization: Bearer 

{
     "description": ""
}


###

PATCH http://localhost:3939/tasks/<insert id>
Content-Type: application/json

{
     "description": ""
}

###
PATCH http://localhost:3939/tasks/647ff274c9247b673875a7b1/complete

###

DELETE http://localhost:3939/tasks/<insert id>